# Pandemic Suite Configuration File		

title = 'Example of a SEIR Configuration File'
date = '2021-04-20'
user = 'Samuel'

[model]
	name = "SEIR-byage-vac2"
	compartments  = ['S','E','I','R'] 
	

[data]
	# Real data will set initial conditions and will be available to be plotted and to calculate errors	
	datafile = false # File path for importing data from file 
	importdata = false # Import data from external source

	# parameters to use when importing from external sources 
	initdate = ''
	country = ''
	state = ''
	county = ''#'13101'
	healthservice = ''
	loc_name= '' # optional 


[parameters]
	[parameters.static]
	t_init = 0 # Initial day
	t_end = 500 # Final day
	timestep = 0.01 # Timestep for solver
	
	# Saturation dynamic
	k_I = 0
	k_R = 0

	seroprevfactor = 1 # Fraction of the total population that take part on the dynamic at the beginning
	expinfection = 0 # Factor in which exposed infect, default is 0

	mu = 0.5 # E(0) = mu*I(0)
	
	# Subreport
	pI_det = 1		
	
	[parameters.dynamic]
	beta = 0.2
	alpha = 1
	
	# External flux rates over time 
	S_f = 0#'{"function":"Events","values":[10000,-10000],"days":[[190,200],[210,220]]}'
	E_f = 0
	I_f = 0
	R_f = 0	
	
	# -------------------------- #
	#   Transition Parameters    # 
	# -------------------------- #	
	# Transition time between exposed and infectious
        tE_I = 5.0 # 1/sigma
	# Transition time between infectious and removed
        tI_R = 10.0 # 1/gamma
	
	# Average Immunity loss rate (1/time)
	rR_S = 0 
	
[initialconditions]
	# total population in area
	population = 100000

	# Recovered	
	R = 0

	# Infected
	# Note: In case real and detected values are >0, real value will be used
	# Active Infected
	I = 0	# Real Infected
	I_det = 100	# Detected Infected

	# New daily Infected
	I_d = 0
	I_d_det = 0	
	
	# Accumulated Infected	
	I_ac = 0
	I_ac_det = 0

	# Leave E and E_d as false for using mu
	E = false
	E_d = false
	

	

